exports.PS2Repositories = [
    {
        "firstLetters": ["#","A"],
        "link": "https://archive.org/download/PS2_COLLECTION_PART1",
    },
    {
        "firstLetters": ["A","B"],
        "link": "https://archive.org/download/PS2_COLLECTION_PART2",
    },
    {
        "firstLetters": ["B"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART3"
    },
    {
        "firstLetters":["B","C"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART4"
    },
    {
        "firstLetters":["C","D"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART5"
    },
    {
        "firstLetters":["D"],
        "link":"https://archive.org/download/ps2_collection_part6_202008"
    },
    {
        "firstLetters":["D"],
        "link":"https://archive.org/download/ps2_collection_part7"
    },
    {
        "firstLetters":["D","E","F"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART8"
    },
    {
        "firstLetters":["F"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART9"
    },
    {
        "firstLetters":["F","G"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART10"
    },
    {
        "firstLetters":["G","H"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART11"
    },
    {
        "firstLetters":["I","J","K"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART12"
    },
    {
        "firstLetters":["K","L","M"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART13"
    },
    {
        "firstLetters":["M"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART14"
    },
    {
        "firstLetters":["M","N"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART15"
    },
    {
        "firstLetters":["N","O"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART16"
    },
    {
        "firstLetters":["O"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART17"
    },
    {
        "firstLetters":["O","P"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART18"
    },
    {
        "firstLetters":["P","Q","R"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART19"
    },
    {
        "firstLetters":["R","S"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART20"
    },
    {
        "firstLetters":["S"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART21"
    },
    {
        "firstLetters":["S"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART22"
    },
    {
        "firstLetters":["S"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART23"
    },
    {
        "firstLetters":["S"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART24"
    },
    {
        "firstLetters":["S","T"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART25"
    },
    {
        "firstLetters":["T"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART26"
    },
    {
        "firstLetters":["T","U","V","W","X","Y","Z"],
        "link":"https://archive.org/download/PS2_COLLECTION_PART27"
    }
]